# ------------------------------------
#   官方手册: https://docs.serverless-devs.com/user-guide/aliyun/#fc3
#   常见小贴士: https://manual.serverless-devs.com/user-guide/tips/
#   有问题快来钉钉群问一下吧：33947367
# ------------------------------------
edition: 1.0.0
name: ai_asr
access: default

vars: 
  region: "{{ region }}"
  serviceName: "ASR"
  functionName: "nim_asr" 
  imageUrlASR: registry.cn-shanghai.aliyuncs.com/aliyun-fc/nim-nvidia-fastpitch-hifigan-tts-1.0.0-fc-1:asr-v1
  imageUrlParakeet: registry.cn-shanghai.aliyuncs.com/aliyun-fc/nim-nvidia-fastpitch-hifigan-tts-1.0.0-fc-1:nim-nvidia-parakeet-ctc-1.1b-asr-1.0.0-fc-1
  apiKey: "{{ apiKey }}"
  service:
    name: ${vars.serviceName}
    description: 'ASR 部署到函数计算'
    internetAccess: true
    logConfig: auto
    vpcConfig: auto
    nasConfig: auto

services:
  # 初始化模型函数
  initial:
    component: fc
    actions: 
      post-deploy:
        - run: s cli fc invoke --timeout 3600 -a {{ access }} --service-name ASR --function-name init --region cn-shanghai && s cli fc provision put --qualifier LATEST --target 1 --enable-idle-billing true -a {{ access }} --service-name ASR --function-name parakeet --region cn-shanghai

        - run: bash ./post-check
    props:
      region: ${vars.region}
      service: ${vars.service}
      function:
        name: init
        description: 模型初始化函数
        handler: main.handler
        timeout: 3600
        diskSize: 512
        codeUri: './initial'
        runtime: python3.10
        cpu: 16
        instanceConcurrency: 1
        # cpu: 8
        memorySize: 32768

  # FrontEnd
  searchfile:
    component: fc
    actions: 
      post-deploy: 
        - component: fc ondemand put --qualifier LATEST --max 1
    props:
      region: "${vars.region}" 
      service: ${vars.service}
      function:
        name: ${vars.functionName}
        description: "NIM_ASR"

        handler: index.handler
        timeout: 600
        diskSize: 512
        caPort: 8501
        # 运行时
        runtime: custom-container
        customContainerConfig:
          args: ''
          accelerationType: Default
          image: ${vars.imageUrlASR}
          accelerationInfo:
            status: Preparing
          command: ''
          webServerMode: true
        # 规格
        instanceConcurrency: 100
        cpu: 8
        memorySize: 32768
        environmentVariables:
          ENTRY_URL: "${parakeet.output.url.system_url}:8089"
          API_KEY: "${vars.apiKey}"

      triggers:
        - name: defaultTrigger
          description: ''
          type: http
          qualifier: LATEST
          config:
            methods:
              - GET
              - POST
              - PUT
              - DELETE
            authType: anonymous
            disableURLInternet: false

      customDomains:
        - domainName: auto
          protocol: HTTP
          routeConfigs:
            - path: /*


  #backend
  parakeet:
    component: fc
    props:
      region: ${vars.region}
      service: ${vars.service}
      function:
        name: "parakeet"
        description: ASR 后端 parakeet 函数

        handler: index.handler
        timeout: 600
        diskSize: 30720
        caPort: 50051
        instanceType: fc.gpu.ada.1

        # 运行时
        runtime: custom-container
        customContainerConfig:
          args: ''
          accelerationType: Default
          image: ${vars.imageUrlParakeet}
          accelerationInfo:
            status: Preparing
          command: ''
          webServerMode: true

        instanceConcurrency: 10
        cpu: 8
        memorySize: 65536
        gpuMemorySize: 49152
        asyncConfiguration: {}

        environmentVariables:
          NGC_API_KEY: "${vars.apiKey}" 
          NIM_CACHE_PATH: "/mnt/auto"
          NIM_HTTP_API_PORT: "9000"
          NIM_MANIFEST_PROFILE: "40d7e326-43f4-11ef-87a2-239b5c506ca7"
          NIMFC_MODEL_EGREP: "parakeet-ctc-riva-1-1b.*l40|punctuation-riva.*l40"
          
      triggers:
        - name: defaultTrigger
          description: ''
          type: http
          qualifier: LATEST
          config:
            methods:
              - GET
              - POST
              - PUT
              - DELETE
            authType: anonymous
            disableURLInternet: false