# ------------------------------------
#   官方手册: https://docs.serverless-devs.com/user-guide/aliyun/#fc3
#   常见小贴士: https://manual.serverless-devs.com/user-guide/tips/
#   有问题快来钉钉群问一下吧：33947367
# ------------------------------------
edition: 1.0.0
name: tts
access: default

vars: 
  region: "cn-shanghai"
  serviceName: "NIM"
  functionName: "nim_tts" 
  imageUrlTTS: registry.cn-shanghai.aliyuncs.com/aliyun-fc/nim-nvidia-fastpitch-hifigan-tts-1.0.0-fc-1:tts-v1
  imageUrlFastpitch: registry.cn-shanghai.aliyuncs.com/aliyun-fc/nim-nvidia-fastpitch-hifigan-tts-1.0.0-fc-1:v1
  apiKey: "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"
  service:
    name: ${vars.serviceName}
    description: 'NIM 部署到函数计算'
    internetAccess: true
    logConfig: auto
    vpcConfig: auto
    nasConfig: auto

services:
  # FrontEnd
  TTS:
    component: fc
    actions: 
      post-deploy: 
        - component: fc ondemand put --qualifier LATEST --max 1
    props:
      region: "${vars.region}" 
      service: ${vars.service}
      function:
        name: ${vars.functionName}
        description: "NIM_TTS"

        handler: index.handler
        timeout: 600
        diskSize: 512
        caPort: 8501
        instanceType: e1
        # 运行时
        runtime: custom-container
        customContainerConfig:
          args: ''
          accelerationType: Default
          image: ${vars.imageUrlTTS}
          accelerationInfo:
            status: Preparing
          command: ''
          webServerMode: true
        # 规格
        instanceConcurrency: 100
        cpu: 8
        memorySize: 32768
        environmentVariables:
          # ENTRY_URL: sgpu-niigan-tts-yous-zhouys-nim-sdnarfwfsu.cn-shanghai.fcapp.run:8089
          ENTRY_URL: "${fastpitch.output.url.system_url}:8089"
      triggers:
        - name: defaultTrigger
          description: ''
          type: http
          qualifier: LATEST
          config:
            methods:
              - GET
              - POST
              - PUT
              - DELETE
            authType: anonymous
            disableURLInternet: false

      customDomains:
        - domainName: auto
          protocol: HTTP
          routeConfigs:
            - path: /*


  #backend
  fastpitch:
    component: fc
    actions: 
      post-deploy: 
        - component: fc provision put --qualifier LATEST --target 1
    props:
      region: ${vars.region}
      service: ${vars.service}
      function:
        name: "Fastpitch"
        description: NIM 后端 Fastpitch 函数

        handler: index.handler
        timeout: 600
        diskSize: 10240
        caPort: 50051
        instanceType: fc.gpu.ada.1

        # 运行时
        runtime: custom-container
        customContainerConfig:
          args: ''
          accelerationType: Default
          image: ${vars.imageUrlFastpitch}
          accelerationInfo:
            status: Preparing
          command: ''
          webServerMode: true

        instanceConcurrency: 100
        cpu: 8
        memorySize: 65536
        gpuMemorySize: 49152
        asyncConfiguration: {}

        environmentVariables:
          NGC_API_KEY: "${vars.apiKey}" 
          NIM_CACHE_PATH: "/mnt/auto"
          NIM_HTTP_API_PORT: "9000"
          NIM_MANIFEST_PROFILE: "713858f8-43f3-11ef-86ee-4f6374fce1aa"
          NIMFC_MODEL_EGREP: "fastpitch-hifigan-riva_ven-us_l40x1_24.06"

      triggers:
        - name: defaultTrigger
          description: ''
          type: http
          qualifier: LATEST
          config:
            methods:
              - GET
              - POST
              - PUT
              - DELETE
            authType: anonymous
            disableURLInternet: false

  initial:
    component: fc
    actions: 
      post-deploy:
        - component: fc invoke --service_name ${this.output.service_name} --function ${this.output.function_name} 
    props:
      region: ${vars.region}
      service: ${vars.service}
      function:
        name: init
        description: 模型初始化函数
        handler: main.handler
        timeout: 3600
        diskSize: 512
        codeUri: './initial'
        runtime: python3.10
        # cpu: 16
        instanceConcurrency: 1
        cpu: 8
        memorySize: 32768